version: '3'
services:
  backend:
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 20 && python main.py"]  # Wait for DB to be ready
    environment:
      - DATABASE_HOST=db  # This matches the service name "db"
      - DATABASE_PORT=3306  # Explicitly specify port for connection
      - DATABASE_USER=appuser
      - DATABASE_PASSWORD=appuserpassword
      - FLASK_APP=manager.py
      - FLASK_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - "8001:5000"
    volumes:
      - .:/app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: maindb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpassword
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33067:3306"  # Ensure the host-port mapping is correct
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s


