version: '3'
services:
  backend:
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 20 && python main.py"]
    environment:
      - DATABASE_HOST=db
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: maindb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpassword
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s